connect 'jdbc:derby:fqdb';

--create schema freequiz;
--CREATE  TABLE IF NOT EXISTS `freeQuiz`.`subjects` (
--  `subjectid` INT NOT NULL AUTO_INCREMENT ,
--  `subject` VARCHAR(45) NULL ,
--  PRIMARY KEY (`subjectid`) )
--ENGINE = InnoDB

create table subjects(
	subjectid INTEGER  NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
	subject VARCHAR(45) NOT NULL
);
	
create table topics(
	topicid INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	topic VARCHAR(45) NOT NULL, 
	gradeLevel INTEGER
);

create table topicSubjects(
	topicid INTEGER ,
	subjectid INTEGER ,
	FOREIGN KEY (topicid) REFERENCES topics(topicid) ON DELETE CASCADE ON UPDATE RESTRICT,
	FOREIGN KEY (subjectid) REFERENCES subjects (subjectid) ON DELETE CASCADE ON UPDATE RESTRICT
);
	
create table questions(
	questionid INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	topicid INTEGER,
	questionText VARCHAR(255) NOT NULL,
	answerText VARCHAR(255) NOT NULL,
	difficulty INTEGER NOT NULL,
	FOREIGN KEY (topicid) REFERENCES topics(topicid) ON DELETE CASCADE ON UPDATE RESTRICT
);

create table class(
	classid INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(45) NOT NULL,
	description VARCHAR(255) 
);

create table students(
	studentid INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(45) NOT NULL
);

create table studentClasses(
	studentid INTEGER,
	classid INTEGER,
	FOREIGN KEY (studentid) REFERENCES students(studentid) ON DELETE CASCADE ON UPDATE RESTRICT,
	FOREIGN KEY (classid) REFERENCES class(classid) ON DELETE CASCADE ON UPDATE RESTRICT
);

insert into subjects values (DEFAULT, 'Math'), (DEFAULT, 'Science'), (DEFAULT, 'Astonomy'), (DEFAULT, 'English'), (DEFAULT, 'Spelling'), (DEFAULT, 'Programming');
insert into topics values (DEFAULT, 'Addition', 1), (DEFAULT, 'Subtraction', 1), (DEFAULT, 'Multiplication', 2), (DEFAULT, 'Sentence Structure', 1);
insert into questions values (DEFAULT, 1, 'What is 2+2?', '4', 1), (DEFAULT, 2, 'What is 2-2?', '0', 1), (DEFAULT, 3,'What is 2x2?', '4', 1), (DEFAULT, 4,'What two components are in every sentence?', 'Subject, Verb', 1);
insert into topicSubjects values (1,1), (2,1), (3,1), (4,4);

-- SELECT DISTINCT gradeLevel FROM topics;
	
disconnect;
exit;